### ISSUE TITLE
Be able to use hiera to specify which controls are enforced and which are monitored on

### ISSUE THREAD

**Issue by jessereynolds** [jessereynolds/cis#2]
Is `noop`ing the controls which are to be monitored the best way to go? Seems the most conventional / straightforward. 

Anyhow, as an operator of a fleet of systems I want to be able to set which CIS sections / controls are to be enforced, and which are to be monitored. 

How might this look? 

Profile to apply: 

```yaml
---
os_compliance::profiles: 
  - CIS-L1-Windows-2012-R2:
    mode: enforce
    exceptions:
      1.1.*: monitor
      1.2.*: monitor
      2.2.3: monitor
      2.2.5: monitor
      2.3.1.*: monitor
      2.3.1.3: enforce

# or more like:

os_compliance::excluded_sections:
  - 'cis::windows::security_options::accounts'

os_compliance::monitored_sections:
  - 'cis::windows::security_options::interactive_logon'
```

Mapping of a profile to a set of controls

```yaml
---
os_security::profile_definitions::cis-l1-windows-2012r2:
  - 


```

```puppet
class os_compliance {
}
```

```puppet
class os_compliance::cis::windows_2012r2_l1::v_2_3_0::rule_1_1_1 (
  Enum['enforce','monitor','skip'] $mode = 'monitor',
) {
  case $mode {
    'monitor' => { 
      $skip = false
      noop()
    }
    'skip' => { $skip = true }
    default => { }
  }
  if $password_history != false {
    local_security_policy { 'Enforce password history':
      ensure       => present,
      policy_value => String($password_history),
      tags => ['cis_windows_2012r2_l1', 'cis_rule_1.1.1'],
    }
  }
}
```

or perhaps

```puppet
class os_compliance::rule::password_history (
  Enum['enforce','monitor'] $mode = 'monitor',
) {
  if $mode == 'monitor' {
    noop()
  }

  local_security_policy { 'Enforce password history':
    ensure       => present,
    policy_value => String($password_history),
  }

}
```
and

```puppet
class os_compliance::apply (
  $rulesets = [],
) {
  $rulesets.each |$ruleset| {
    lookup("os_compliance::ruleset::${ruleset}").each |$rule, $mode| {
      $rule_class = lookup("os_compliance::rule_alias::${rule}")
      class { "os_compliance::rule::${rule_class}":
        mode => $mode,
      }
    }
  }
}
```

```yaml
os_compliance::apply::rulesets:
  'cis-l1-ms-windows-2012r2-2.3.0'

os_compliance::ruleset::cis-l1-ms-windows-2012r2-2.3.0:
  cis_1.1.1: enforce
  cis_1.1.2: monitor
  cis_1.1.3: enforce

os_compliance::ruleset::cis-l1-ms-windows-2008r2-3.1.0:
  cis_1.1.1: monitor
  cis_1.1.2: monitor
  cis_1.1.3: monitor

os_compliance::rule_alias::cis_1.1.1: password_history
os_compliance::rule_alias::cis_1.1.2: maximum_password_age
 
```
